### ISSUE TITLE
Exclude of Model Files

### ISSUE THREAD

**Issue by team4music** [tomrus88/CASCExplorer#5]
Thanks for your Software, could it be possible to stop the model files from expcuding within https://github.com/WoW-Tools/CASCExplorer/blob/v0.9-alpha/CASCExplorer/FileScanner.cs

Sincerly Yours

Joel

PS: It seems not to be possible to get in contact with you by mail. I would be happy if you can get in contact with me info AT gnitter .de

**Comment by tomrus88** [comment]
Model files aren't excluded from scanning.
