### ISSUE TITLE
D3 Stringlist Language

### ISSUE THREAD

**Issue by jeffrey-vella** [tomrus88/CASCExplorer#6]
Stringlist files (.stl) extract in German, my client is in English. Selecting a different locale doesn't change it. Issue has existed for a while in previous versions. Would appreciate greatly appreciate a way to get at localized version of the files.

**Comment by tomrus88** [comment]
Fixed in https://github.com/WoW-Tools/CASCExplorer/commit/f2d0f54d1f908d5e2c474dc48c1eb94817ac5d54.
